languageCode: "en-us"
baseUrl: "https://maciej.litwiniuk.net"
title: "Maciej Litwiniuk"
theme: "anubis"
paginate: 10
# disqusShortname: "yourdiscussshortname"
# googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0

taxonomies:
  category: categories

params:
  author: "Maciej Litwiniuk"
  email: maciej@litwiniuk.net # used for microformats
  avatar: "/images/mua-bday-500.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: "mlitwiniuk/maciej.litwiniuk.net"  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  graphcommentId: ""
  plausibleAnalytics:
    domain: maciej.litwiniuk.net
  webmentions:
    login: maciej.litwiniuk.net
    pingback: true
  social:
  - id: github
    name: mlitwiniuk
  - id: twitter
    name: mlitwiniuk
  - id: instagram
    name: maciejlitwiniuk
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true
